apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kagent

resources:
  - rbac/mcp-kubernetes.yaml
  - mcp/servers.yaml
  - gateway/configmap.yaml
  - gateway/deployment.yaml
  - gateway/service.yaml
  - integration/bundles/remote
  - integration/bundles/byo
